[".config/vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "72h"
[".local/bin"]
    type = "archive"
    url = "https://github.com/cantino/mcfly/releases/download/v0.6.0/mcfly-v0.6.0-x86_64-unknown-linux-musl.tar.gz"
    executable = true
{{ if .is_personal -}}
[".go"]
    type = "archive"
    url = "https://dl.google.com/go/go1.17.4.linux-amd64.tar.gz"
    exact = true
    stripComponents = 1
{{- end }}
{{ if .needs_terminal -}}
[".local/share/fonts/FiraCode"]
    type = "archive"
    url = "https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip"
    exact = true
    stripComponents = 1
[".local/share/fonts/JetBrainsMono"]
    type = "archive"
    url = "https://github.com/JetBrains/JetBrainsMono/releases/download/v2.242/JetBrainsMono-2.242.zip"
    exact = true
    stripComponents = 1
{{- end }}
