[".local/bin/extract"]
    type = "file"
{{ if eq .chezmoi.os "darwin" }}
    url = "https://github.com/bedecarroll/extract/releases/latest/download/extract-macos-aarch64"
{{ else }}
    url = "https://github.com/bedecarroll/extract/releases/latest/download/extract-linux-x86_64"
{{ end }}
    executable = true
    refreshPeriod = "72h"
[".local/bin/macfmt"]
    type = "file"
{{ if eq .chezmoi.os "darwin" }}
    url = "https://github.com/bedecarroll/macfmt/releases/latest/download/macfmt-macos-aarch64"
{{ else }}
    url = "https://github.com/bedecarroll/macfmt/releases/latest/download/macfmt-linux-x86_64"
{{ end }}
    executable = true
    refreshPeriod = "72h"
[".local/bin/ripgrep"]
    type = "file"
{{ if eq .chezmoi.os "darwin" }}
    url = "https://github.com/bedecarroll/ripgrep/releases/latest/download/ripgrep-macos-aarch64"
{{ else }}
    url = "https://github.com/bedecarroll/ripgrep/releases/latest/download/ripgrep-linux-x86_64"
{{ end }}
    executable = true
    refreshPeriod = "72h"
[".config/vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "72h"
{{ if .needs_terminal -}}
[".local/share/fonts/FiraCode"]
    type = "archive"
    url = "https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip"
    exact = true
    stripComponents = 1
[".local/share/fonts/JetBrainsMono"]
    type = "archive"
    url = "https://github.com/JetBrains/JetBrainsMono/releases/download/v2.242/JetBrainsMono-2.242.zip"
    exact = true
    stripComponents = 1
{{- end }}
