[".local/bin/tx"]
    type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
    url = "https://github.com/bedecarroll/tool-executor/releases/latest/download/tx-aarch64-apple-darwin.tar.gz"
{{ else }}
    url = "https://github.com/bedecarroll/tool-executor/releases/latest/download/tx-x86_64-unknown-linux-gnu.tar.gz"
{{ end }}
    executable = true
    refreshPeriod = "72h"
    path = "tx"
    stripComponents = 1
[".local/bin/pa"]
    type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
    url = "https://github.com/bedecarroll/prompt-assembler/releases/latest/download/pa-aarch64-apple-darwin.tar.gz"
{{ else }}
    url = "https://github.com/bedecarroll/prompt-assembler/releases/latest/download/pa-x86_64-unknown-linux-gnu.tar.gz"
{{ end }}
    executable = true
    refreshPeriod = "72h"
    path = "pa"
    stripComponents = 1
[".local/bin/cfgcut"]
    type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
    url = "https://github.com/bedecarroll/cfgcut/releases/latest/download/cfgcut-aarch64-apple-darwin.tar.xz"
{{ else }}
    url = "https://github.com/bedecarroll/cfgcut/releases/latest/download/cfgcut-x86_64-unknown-linux-gnu.tar.xz"
{{ end }}
    executable = true
    refreshPeriod = "72h"
    path = "cfgcut"
    stripComponents = 1
[".local/bin/extract"]
    type = "file"
{{ if eq .chezmoi.os "darwin" }}
    url = "https://github.com/bedecarroll/extract/releases/latest/download/extract-macos-aarch64"
{{ else }}
    url = "https://github.com/bedecarroll/extract/releases/latest/download/extract-linux-x86_64"
{{ end }}
    executable = true
    refreshPeriod = "72h"
[".local/bin/macfmt"]
    type = "file"
{{ if eq .chezmoi.os "darwin" }}
    url = "https://github.com/bedecarroll/macfmt/releases/latest/download/macfmt-macos-aarch64"
{{ else }}
    url = "https://github.com/bedecarroll/macfmt/releases/latest/download/macfmt-linux-x86_64"
{{ end }}
    executable = true
    refreshPeriod = "72h"
[".local/bin/ripcalc"]
    type = "file"
{{ if eq .chezmoi.os "darwin" }}
    url = "https://github.com/bedecarroll/ripcalc/releases/latest/download/ripcalc-macos-aarch64"
{{ else }}
    url = "https://github.com/bedecarroll/ripcalc/releases/latest/download/ripcalc-linux-x86_64"
{{ end }}
    executable = true
    refreshPeriod = "72h"
[".config/vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "72h"
{{ if .needs_terminal -}}
[".local/share/fonts/FiraCode"]
    type = "archive"
    url = "https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip"
    exact = true
    stripComponents = 1
[".local/share/fonts/JetBrainsMono"]
    type = "archive"
    url = "https://github.com/JetBrains/JetBrainsMono/releases/download/v2.242/JetBrainsMono-2.242.zip"
    exact = true
    stripComponents = 1
{{- end }}
