keys:
  - &age_keys >-
    age1yubikey1qwzq9klxc03flzl4k5lt5kc43jxxcht9ncu9vvwggy6qmt66w6nqu5cc5du,
    age1g6w5097k0j8ccp7ksc5mt0wa6w8657ausuk4tkn2vdwg6lz8c9ssazqryw
  - &euler >-
    age1w8r39s2u2fcjhpm5yw6wzjf9je2u08p3uaqmp5rpjkdef2f6dcns5vyk8w
  - &pascal >-
    age13n2rpycj9763409csx6z2gxz29jswy3q473a6fazkxjdmkj4cdpq7w2dnl

creation_rules:
  - path_regex: nix/shared-secrets\.sops\.yaml$
    key_groups:
      - age:
          - *age_keys
          - *euler
          - *pascal
  - path_regex: nix/system-configs/euler/secrets\.sops\.yaml$
    key_groups:
      - age:
          - *age_keys
          - *euler
  - path_regex: nix/system-configs/pascal/secrets\.sops\.yaml$
    key_groups:
      - age:
          - *age_keys
          - *pascal
