#!/usr/bin/env bash

if command -v brew >/dev/null 2>&1; then
  BREW_PREFIX="${HOMEBREW_PREFIX:-$(brew --prefix)}"
  if [[ -r "$BREW_PREFIX/etc/profile.d/bash_completion.sh" ]]; then
    source "$BREW_PREFIX/etc/profile.d/bash_completion.sh"
  fi
fi
