#!/usr/bin/env bash

# Import nix. If we aren't on a nix system just return as atuin etc won't be there
NIX_PATH="${NIX_PATH:+$NIX_PATH:}$HOME/.nix-defexpr/channels"
if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
  export NIX_PATH
  source "$HOME/.nix-profile/etc/profile.d/nix.sh"
elif [ -e "/nix/var/nix/profiles/default/etc/profile.d/nix.sh" ]; then
  export NIX_PATH
  source "/nix/var/nix/profiles/default/etc/profile.d/nix.sh"
elif [ ! -d "/nix/" ]; then
  return 233
fi

# Source nix completions
if [ -d "$HOME/.nix-profile/share/bash-completion" ]; then
  for COMPLETION in "$HOME/.nix-profile/share/bash-completion/completions/"*; do
    [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
  done
fi
