#!/usr/bin/env bash

# Know who is owning your shell (great when you're in vim)
# NOTE: we want the parent command name so this shellcheck is invalid
# shellcheck disable=SC2009
parent_command_name=$(ps -o comm $PPID | tail -n -1 | rev | cut -f1 -d'/' | rev)
if echo "$parent_command_name" | grep -qE 'tmux|etterminal|mosh|init|Relay|wezterm'; then
  shellparent=''
else
  shellparent="[$parent_command_name]"
fi
export PROMPT_COMMAND='PS1="[\$?][\j]$shellparent \u@$(hostname)\$ "'
