#!/usr/bin/env bash

# Might need to restart shell after first run due to nix install
if command -v bat &>/dev/null; then
  export PAGER='bat'
  # See https://github.com/sharkdp/bat/issues/3053#issuecomment-2259573578
  export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"
  alias cat='bat'
  alias less='bat'
  alias more='bat'
fi
