[misc]
# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
disable = [
  "home_manager",
  "micro",
  "nix",
  "node",
  "poetry",
  "vagrant",
  "vim",
  "vscode",
]
